name: C++ Qt client tests CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python packages
        run: pip install aqtinstall

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Install Qt
        run: |
          python3 -m aqt install-qt linux desktop 6.7.1 gcc_64 --outputdir ${{ github.workspace }}/Qt

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/6.7.1/gcc_64 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Qt Tests
        run: |
          cd build
          ctest --output-on-failure